version: 2
jobs:
  build:
    working_directory: ~/numbers2words
    docker:
      - image: circleci/clojure:lein-2.8.1
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: numbers2words-{{ checksum "project.clj" }}
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: numbers2words-{{ checksum "project.clj" }}
      - run: lein do test, uberjar       


